AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IaC for creating the ELT resources for the data pipeline + Notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 128

Parameters:
  Client:
    Type: String
    Description: Client Name ${Client}
  API:
    Type: String
    Description: Name of the API or Project ${API}
  ENV:
    Type: String
    Description: Deploy environment (possible values test-prod) ${ENV}
  AWSACCOUNT:
    Type: String
    Description: Account id ${AWSACCOUNT}
    Default: ""
  BUCKET:
    Type: String
    Description: Name of the bucket where the data is stored
    Default: ""
  KeyId:
    Type: String
    Description: Id of the KMS Key that decrypts the SSM parameter
    Default: ""
  HOST:
    Type: String
    Description: Host of RDS database destiny
  SECRET:
    Type: String
    Description: Name of the secret with RDS credentials
  SECRETARN:
    Type: String
    Description: Arn of the secret with RDS credentials


Resources:
  StepFunctionETL:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Name: !Sub ${Client}-${API}-Amendment-derivates-ETL-${ENV}
      DefinitionUri: step_function_derivates_definition.asl.json
      DefinitionSubstitutions: 
        GetAmendmentInfoFunctionArn: !GetAtt GetAmendmentInfoFunction.Arn
        GetAmendmentActionsFunctionArn: !GetAtt GetAmendmentActionsFunction.Arn
        GetAmendmentAmendmentsFunctionArn: !GetAtt GetAmendmentAmendmentsFunction.Arn
        GetAmendmentCosponsorsFunctionArn: !GetAtt GetAmendmentCosponsorsFunction.Arn
        GetAmendmentTextFunctionArn: !GetAtt GetAmendmentTextFunction.Arn
        RenameInputFileFunctionArn: !Sub "arn:aws:lambda:us-east-1:${AWSACCOUNT}:function:vt-congress-rename_input_file-test"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAmendmentInfoFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAmendmentActionsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAmendmentAmendmentsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAmendmentCosponsorsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAmendmentTextFunction
        - LambdaInvokePolicy:
            FunctionName:  "vt-congress-rename_input_file-test"
        - "CloudWatchEventsFullAccess"
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource:
            - !Sub arn:aws:states:us-east-1:${AWSACCOUNT}:stateMachine:${Client}-${API}-Amendment-derivates-ETL-${ENV}
          - Effect: Allow
            Action:
            - states:DescribeExecution
            - states:StopExecution
            Resource: "*"
          - Effect: Allow
            Action:
            - events:PutTargets
            - events:PutRule
            - events:DescribeRule
            Resource:
            - !Sub arn:aws:events:us-east-1:${AWSACCOUNT}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*

  GetAmendmentInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Client}-${API}-get_amendment-info-${ENV}
      CodeUri: get_amendment_info/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          API_NAME: !Sub ${API}
          PROJECT_NAME: !Sub ${Client}
          ENV: !Sub ${ENV}
          BUCKET: !Sub ${BUCKET}
          HOST: !Sub ${HOST}
          SECRET: !Sub ${SECRET}
      Architectures:
        - x86_64
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Sub ${KeyId}
        - SSMParameterReadPolicy:
            ParameterName: congress-apikey
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*
        - Version: '2012-10-17'
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - !Sub ${SECRETARN}
  
  GetAmendmentActionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Client}-${API}-get_amendment-actions-${ENV}
      CodeUri: get_amendment_actions/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          API_NAME: !Sub ${API}
          PROJECT_NAME: !Sub ${Client}
          ENV: !Sub ${ENV}
          BUCKET: !Sub ${BUCKET}
          HOST: !Sub ${HOST}
          SECRET: !Sub ${SECRET}
      Architectures:
        - x86_64
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Sub ${KeyId}
        - SSMParameterReadPolicy:
            ParameterName: congress-apikey
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*
        - Version: '2012-10-17'
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - !Sub ${SECRETARN}

  GetAmendmentAmendmentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Client}-${API}-get_amendment-amendments-${ENV}
      CodeUri: get_amendment_amendments/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          API_NAME: !Sub ${API}
          PROJECT_NAME: !Sub ${Client}
          ENV: !Sub ${ENV}
          BUCKET: !Sub ${BUCKET}
          HOST: !Sub ${HOST}
          SECRET: !Sub ${SECRET}
      Architectures:
        - x86_64
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Sub ${KeyId}
        - SSMParameterReadPolicy:
            ParameterName: congress-apikey
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*
        - Version: '2012-10-17'
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - !Sub ${SECRETARN}

  GetAmendmentCosponsorsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Client}-${API}-get_amendment-cosponsors-${ENV}
      CodeUri: get_amendment_cosponsors/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          API_NAME: !Sub ${API}
          PROJECT_NAME: !Sub ${Client}
          ENV: !Sub ${ENV}
          BUCKET: !Sub ${BUCKET}
          HOST: !Sub ${HOST}
          SECRET: !Sub ${SECRET}
      Architectures:
        - x86_64
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Sub ${KeyId}
        - SSMParameterReadPolicy:
            ParameterName: congress-apikey
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*
        - Version: '2012-10-17'
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - !Sub ${SECRETARN}

  GetAmendmentTextFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Client}-${API}-get_amendment-text-${ENV}
      CodeUri: get_amendment_text/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          API_NAME: !Sub ${API}
          PROJECT_NAME: !Sub ${Client}
          ENV: !Sub ${ENV}
          BUCKET: !Sub ${BUCKET}
          HOST: !Sub ${HOST}
          SECRET: !Sub ${SECRET}
      Architectures:
        - x86_64
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Sub ${KeyId}
        - SSMParameterReadPolicy:
            ParameterName: congress-apikey
        - Version: '2012-10-17'
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - !Sub arn:aws:s3:::${BUCKET}
            - !Sub arn:aws:s3:::${BUCKET}/*
        - Version: '2012-10-17'
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
            - !Sub ${SECRETARN}
 
